DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS POSITION;
DROP TABLE IF EXISTS JAPANESE_LVL;
DROP TABLE IF EXISTS EMPLOYEE;

COMMIT;

--DEPARTMENT TABLE
CREATE TABLE DEPARTMENT(
	dept_id VARCHAR(5) NOT NULL,
	dept_name VARCHAR(25) NOT NULL,
	PRIMARY KEY(dept_id)
);

--POSITION TABLE
CREATE TABLE POSITION(
	post_id VARCHAR(5) NOT NULL,
	post_name VARCHAR(25) NOT NULL,
	PRIMARY KEY(post_id)
);

--JAPANESE LEVEL TABLE
CREATE TABLE JAPANESE_LVL(
	jp_lvl_id VARCHAR(5) NOT NULL,
	jp_lvl VARCHAR(15) NOT NULL,
	PRIMARY KEY(jp_lvl_id)
);

--EMPLOYEE TABLE
CREATE TABLE EMPLOYEE(
	id SERIAL NOT NULL,
	emp_id VARCHAR(5) UNIQUE NOT NULL,
	emp_name VARCHAR(50) NOT NULL,
	email VARCHAR(256) NOT NULL,
	ph_no VARCHAR(15) NOT NULL,
	dob DATE NOT NULL,
	gender VARCHAR(10) NOT NULL,
	martial_status VARCHAR(10) NOT NULL,
	join_date DATE NOT NULL,
	dept_id VARCHAR(5) NOT NULL,
	post_id VARCHAR(5) NOT NULL,
	jp_lvl_id VARCHAR(5) NOT NULL,
	password VARCHAR(25) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (dept_id) REFERENCES DEPARTMENT (dept_id),
	FOREIGN KEY (post_id) REFERENCES POSITION (post_id),
	FOREIGN KEY (jp_lvl_id) REFERENCES JAPANESE_LVL (jp_lvl_id)
);